# -*- coding: utf-8 -*-
"""Flight.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zETvXweQII7mxNcdtt4NNNa3W3KU8FyB
"""

from datetime import date
from numbers import Integral
import math

class Flight:
    # There are three valid fare classes for Potter Airlines
    available_classes = {"Economy", "Premium", "Business"}

    # Construct a Flight object
    def __init__(
        self,
        flight_id,
        route,
        origin,
        destination,
        fare_class,
        departure_date,
        day_of_week,
        is_weekend,
        season,
        is_holiday,
        days_to_departure,
        departure_hour,
        capacity,
        class_capacity,
        base_fare,
        historical_avg_route_demand,
        route_popularity,
        seats_remaining,
        current_load_factor,
    ):
        self.flight_id = flight_id
        self.route = route
        self.origin = origin
        self.destination = destination
        self.fare_class = fare_class
        self.departure_date = departure_date
        self.day_of_week = int(day_of_week)   # Convert to integer for consistent validation
        self.is_weekend = is_weekend
        self.season = season
        self.is_holiday = is_holiday
        self.days_to_departure = int(days_to_departure)
        self.departure_hour = int(departure_hour)
        self.capacity = capacity
        self.class_capacity = class_capacity
        self.base_fare = base_fare
        self.historical_avg_route_demand = historical_avg_route_demand
        self.route_popularity = route_popularity
        self.seats_remaining = seats_remaining
        self.current_load_factor = current_load_factor

    # Validate important business rules and check that stored values are internally consistent.
    # The tolerance allows for the three-decimal rounding used in the source dataset.
    def validate(self, load_factor_tolerance=0.01):

        if load_factor_tolerance < 0:
            raise ValueError("load_factor_tolerance cannot be negative.")

        if not self.flight_id:
            raise ValueError("flight_id must not be empty.")

        if not self.route:
            raise ValueError("route must not be empty.")

        if not self.origin or not self.destination:
            raise ValueError("origin and destination must not be empty.")

        if self.fare_class not in self.available_classes:
            raise ValueError(
                f"Unknown fare class: {self.fare_class}. "
                f"Expected one of {sorted(self.available_classes)}."
            )

        if not self.departure_date:
            raise ValueError("departure_date must not be empty.")

        # The dataset stores departure dates by using the YYYY-MM-DD format.
        try:
            parsed_departure_date = date.fromisoformat(str(self.departure_date))
        except (TypeError, ValueError) as exc:
            raise ValueError("departure_date must use YYYY-MM-DD format.") from exc

        # Checked separately to avoid accepting True/False as weekdays.
        if not isinstance(self.day_of_week, int) or isinstance(self.day_of_week, bool):
            raise ValueError("day_of_week must be an integer from 0 to 6.")

        if not 0 <= self.day_of_week <= 6:
            raise ValueError("day_of_week must be between 0 and 6.")

        # The stored weekday should be the same as the actual departure date.
        if parsed_departure_date.weekday() != self.day_of_week:
            raise ValueError("day_of_week is inconsistent with departure_date.")

        if isinstance(self.capacity, bool) or not isinstance(self.capacity, Integral):
            raise ValueError("capacity must be a positive integer.")

        if self.capacity <= 0:
            raise ValueError("Total aircraft capacity must be greater than zero.")

        if isinstance(self.class_capacity, bool) or not isinstance(self.class_capacity, Integral):
            raise ValueError("class_capacity must be a positive integer.")

        if self.class_capacity <= 0:
            raise ValueError("Cabin class capacity must be greater than zero.")

        # The seats in the cabin cannot exceed the total number of seats on the aircraft.
        if self.class_capacity > self.capacity:
            raise ValueError("class_capacity cannot exceed total aircraft capacity.")

        if isinstance(self.seats_remaining, bool) or not isinstance(self.seats_remaining, Integral):
            raise ValueError("seats_remaining must be an integer.")

        # seats_remaining belongs to this cabin class, so class_capacity should be the upper bound.
        if not 0 <= self.seats_remaining <= self.class_capacity:
            raise ValueError("seats_remaining must be between 0 and class_capacity.")

        if not isinstance(self.days_to_departure, int) or isinstance(self.days_to_departure, bool):
            raise ValueError("days_to_departure must be an integer.")

        if self.days_to_departure < 0:
            raise ValueError("days_to_departure cannot be negative.")

        if not isinstance(self.departure_hour, int) or isinstance(self.departure_hour, bool):
            raise ValueError("departure_hour must be an integer from 0 to 23.")

        if not 0 <= self.departure_hour <= 23:
            raise ValueError("departure_hour must be between 0 and 23.")

        if not self.season:
            raise ValueError("season must not be empty.")

        if self.is_weekend not in (True, False, 0, 1):
            raise ValueError("is_weekend must be a boolean value.")

        if self.is_holiday not in (True, False, 0, 1):
            raise ValueError("is_holiday must be a boolean value.")

        # Weekend status is derived from the weekday, so they should be consistent.
        if bool(self.is_weekend) != (self.day_of_week >= 5):
            raise ValueError("is_weekend is inconsistent with day_of_week.")

        if not math.isfinite(self.base_fare) or self.base_fare <= 0:
            raise ValueError("base_fare must be a finite positive number.")

        # Validate the demand inputs by using their respective ranges.
        if not 0 < self.historical_avg_route_demand <= 1:
            raise ValueError("historical_avg_route_demand must be between 0 and 1.")

        if not 0 <= self.route_popularity <= 1:
            raise ValueError("route_popularity must be between 0 and 1 inclusive.")

        # Keep the combined route field consistent with its origin and destination components.
        expected_route = f"{self.origin}-{self.destination}"
        if self.route != expected_route:
            raise ValueError(
                f"route does not match origin and destination: expected {expected_route}."
            )

        if not 0 <= self.current_load_factor <= 1:
            raise ValueError("current_load_factor must be between 0 and 1.")

        # Recalculate load factor from cabin inventory to check the stored database value.
        calculated_load_factor = self.calculate_load_factor()
        if abs(calculated_load_factor - self.current_load_factor) > load_factor_tolerance:
            raise ValueError(
                "current_load_factor is inconsistent with seats_remaining and class_capacity."
            )

        return True

    # Calculate the proportion of occupied seats in this fare class.
    def calculate_load_factor(self):
        # Use class_capacity because seats_remaining only describes this cabin class, not the whole aircraft.
        return 1 - (self.seats_remaining / self.class_capacity)

    # Calculate the proportion of available seats in this fare class.
    def available_seat_ratio(self):
        return self.seats_remaining / self.class_capacity

    # Check whether the cabin is close to sold out using a load-factor threshold.
    def is_nearly_full(self, threshold=0.85):
        if not 0 <= threshold <= 1:
            raise ValueError("threshold must be between 0 and 1.")
        return self.calculate_load_factor() >= threshold

    # Book seats in the fare class and update the flight's in-memory inventory state.
    def book_seats(self, number_of_seats):
        # Booking only positive seats to avoid invalid inventory updates.
        if isinstance(number_of_seats, bool) or not isinstance(number_of_seats, Integral):
            raise ValueError("number_of_seats must be a positive integer.")

        if number_of_seats <= 0:
            raise ValueError("number_of_seats must be greater than zero.")

        if number_of_seats > self.seats_remaining:
            raise ValueError(
                "Cannot book more seats than are currently available in this fare class."
            )

        self.seats_remaining -= number_of_seats

        # Recalculate the stored load factor so the object stays internally consistent after booking.
        self.current_load_factor = self.calculate_load_factor()
        return self.seats_remaining

    # Convert the Flight object into a dictionary for display, Pandas/SQL update.
    def to_dict(self):
        return {
            "flight_id": self.flight_id,
            "route": self.route,
            "origin": self.origin,
            "destination": self.destination,
            "fare_class": self.fare_class,
            "departure_date": self.departure_date,
            "day_of_week": self.day_of_week,
            "is_weekend": self.is_weekend,
            "season": self.season,
            "is_holiday": self.is_holiday,
            "days_to_departure": self.days_to_departure,
            "departure_hour": self.departure_hour,
            "capacity": self.capacity,
            "class_capacity": self.class_capacity,
            "base_fare": self.base_fare,
            "historical_avg_route_demand": self.historical_avg_route_demand,
            "route_popularity": self.route_popularity,
            "seats_remaining": self.seats_remaining,
            "current_load_factor": self.current_load_factor,
        }

    # Return a readable summary.
    def summary(self):
        return (
            f"{self.flight_id} | {self.route} | {self.fare_class} | "
            f"{self.days_to_departure} days | "
            f"{self.seats_remaining}/{self.class_capacity} seats remaining | "
            f"route popularity: {self.route_popularity:.2f}"
        )